"""Give real lesson headings stable anchors and build the offline section catalog."""

from __future__ import annotations

import json
import os
import re
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"}
WORKSHOP_TITLES = {
    "contract": "输入输出契约", "dataflow": "模块数据流图",
    "source-walkthrough": "核心源码精讲", "build-it": "动手设计与验收",
    "trace": "数据演算", "worked-example": "数据演算",
    "boundaries": "边界与不变量", "invariants": "边界与不变量", "self-test": "独立推理练习",
}


class Headings(HTMLParser):
    def __init__(self, source):
        super().__init__()
        self.source = source
        self.offsets = [0]
        for line in source.splitlines(keepends=True):
            self.offsets.append(self.offsets[-1] + len(line))
        self.stack = []
        self.sections = []
        self.edits = []
        self.heading = None
        self.used = set(re.findall(r'\bid="([^"]+)"', source))

    def handle_starttag(self, tag, pairs):
        attrs = dict(pairs)
        blocked = any(set(a.get("class", "").split()) & {"empty-state", "evidence"} for _, a in self.stack)
        if tag == "h2" and not blocked:
            section = next((a.get("id") for t, a in reversed(self.stack) if t == "section" and a.get("id")), None)
            anchor = attrs.get("id") or section
            if not anchor or any(item["id"] == anchor for item in self.sections):
                number = len(self.sections) + 1
                anchor = f"reading-section-{number:02}"
                while anchor in self.used:
                    number += 1
                    anchor = f"reading-section-{number:02}"
                self.used.add(anchor)
                line, col = self.getpos()
                self.edits.append((self.offsets[line - 1] + col + 3, f' id="{anchor}"'))
            self.heading = {"id": anchor, "text": []}
        if tag not in VOID:
            self.stack.append((tag, attrs))

    def handle_endtag(self, tag):
        if tag == "h2" and self.heading is not None:
            self.sections.append({"id": self.heading["id"], "title": " ".join("".join(self.heading["text"]).split())})
            self.heading = None
        for index in range(len(self.stack) - 1, -1, -1):
            if self.stack[index][0] == tag:
                del self.stack[index:]
                break

    def handle_data(self, text):
        if self.heading is not None:
            self.heading["text"].append(text)


def main():
    inventory = {}
    for page in sorted(ROOT.glob("chapters/**/*.html")):
        source = page.read_text(encoding="utf-8")
        parser = Headings(source)
        parser.feed(source)
        for offset, value in reversed(parser.edits):
            source = source[:offset] + value + source[offset:]
        for item in parser.sections:
            if page.name == "workshop.html":
                item["title"] = WORKSHOP_TITLES.get(item["id"], item["title"])
        if page.name == "workshop.html":
            source = re.sub(r'(<a\b[^>]*href="#(contract|dataflow|source-walkthrough|build-it)"[^>]*>)[^<]*(</a>)', lambda m: m[1] + WORKSHOP_TITLES[m[2]] + m[3], source)
        inventory[page.relative_to(ROOT).as_posix()] = parser.sections
        if "assets/reading-navigation.js" not in source:
            base = Path(os.path.relpath(ROOT / "assets", page.parent)).as_posix()
            extra = f'<script defer src="{base}/sections.js"></script><script defer src="{base}/reading-navigation.js"></script>'
            source, count = re.subn(r'(<script\b[^>]*src="[^"]*/navigation.js"[^>]*></script>)', lambda m: m[1] + extra, source, count=1)
            assert count == 1, f"No shared navigation script: {page}"
        page.write_text(source, encoding="utf-8")
    (ROOT / "assets/sections.js").write_text("// Generated by tools/build_reading_navigation.py; do not edit by hand.\nwindow.STUDY_SECTIONS = " + json.dumps(inventory, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8")
    print(f"Reading navigation built: {len(inventory)} lessons, {sum(map(len, inventory.values()))} anchored sections.")


if __name__ == "__main__":
    main()
